name: Deploy to Kubernetes

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Kubernetes cluster
              uses: azure/k8s-set-context@v1
              with:
                kubeconfig: ${{ secrets.KUBECONFIG }}

            - name: Deploy to Kubernetes
              run: kubectl apply -f deployment.yaml